# 选项卡的工作流名称
name: GoodLive Pages

# 定义工作流触发的事件
on:
  # 要从ui手动运行此工作流
  workflow_dispatch:
  # 添加 push 事件，以便每次将提交推送到名为 main 的分支时，工作流都会自动运行
  push:
    branches:
      - main
  # 添加 pull_request 事件，以便每次创建或更新拉取请求时，工作流都会自动运行
  pull_request:

# 修改授予 GITHUB_TOKEN 的默认权限
permissions:
  contents: read
  pull-requests: read

# 为特定事件创建并发组，并使用 || 运算符定义回退值（取消同一并发组中任何当前正在运行的作业或工作流）


# 将工作流文件中运行的所有作业组合在一起
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.13.x
          cache: npm
        
      - name: GetLastLog
        id: git_log
        uses: Edisonboy/lastest-git-log-action@main
        with:
          tag: origin/main

      - name: npm install and build
        run: npm install
             npm run build    

        
  
